version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/vgs_chatbot
      - JWT_SECRET=${JWT_SECRET:-change-this-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SHAREPOINT_SITE_URL=${SHAREPOINT_SITE_URL}
    depends_on:
      - db
    volumes:
      - ./vgs_chatbot:/app/vgs_chatbot
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vgs_chatbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Optional: PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: