from typing import Iterable, Iterator, Sequence

class TextEmbedding:
    def __init__(self, *, model_name: str | None = ...) -> None: ...
    def embed(
        self, texts: Iterable[str], *, batch_size: int | None = ...
    ) -> Iterator[Sequence[float]]: ...
