name: Test Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Set your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start streamlit app
      run: |
        timeout 10s streamlit run src/vgs-chatbot/streamlit_app.py &
        sleep 5 # Wait for the server to start
        
    - name: Test streamlit app
      run: |
        curl http://localhost:8501 # Attempt to make a request to the app
